//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preorders
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public System.DateTime SignUpDate { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
